import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import StyledComponentsRegistry from "@/lib/registry";
import { StyledThemeProvider } from "@/lib/themeProvider";
import { ChildrenWrapper } from "@/interfaces/common";
import Navigation from "@/components/_common/Navigation";
import GlobalStyles from "@/styles/GlobalStyles";
import StoreProvider from "@/lib/StoreProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<ChildrenWrapper>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <StoreProvider>
          <StyledComponentsRegistry>
            <StyledThemeProvider>
              <GlobalStyles />
              <Navigation />
              {children}
            </StyledThemeProvider>
          </StyledComponentsRegistry>
        </StoreProvider>
      </body>
    </html>
  );
}
