import type { Metadata } from "next";

import { ChildrenWrapper } from "@/interfaces/common";
import StyledComponentsRegistry from "@/lib/registry";
import { StyledThemeProvider } from "@/lib/themeProvider";
import StoreProvider from "@/lib/StoreProvider";
import ReactQueryClientProvider from "@/lib/QueryClientProvider";

import Navigation from "@/components/_common/Navigation";
import GlobalStyles from "@/styles/GlobalStyles";
import { FormsProvider } from "@/context/FormContext";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<ChildrenWrapper>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ReactQueryClientProvider>
          <StoreProvider>
            <StyledComponentsRegistry>
              <StyledThemeProvider>
                <GlobalStyles />
                <Navigation />
                <FormsProvider>{children}</FormsProvider>
              </StyledThemeProvider>
            </StyledComponentsRegistry>
          </StoreProvider>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
